accounts/urls.py
"""
 BBofUser: Account Framework top level

"""
from django.conf.urls import (patterns,
                              include,
                              url)
from django.contrib import admin

from accounts.views.user import (verify_phone, user_edit)
from accounts.views.other import (manage_account, logout, login)
from accounts.views.sms import (sms_code, sms_login)

admin.autodiscover()

# TODO: Implement Education Pages
# TODO: Replace Register Page with Education Page
# TODO: Add Link to Medicare Registration Page if User Not in LDAP

# DONE: Identify Modules that require accounts.session_master decorator
urlpatterns = patterns('',
                       # Examples:
                       url(r'^login$',
                           'accounts.views.sms.sms_login',
                           name='login'),
                       url(r'smscode/',
                           'accounts.views.sms.sms_code',
                           name='sms_code'),
                       url(r'^logout$',
                           'accounts.views.logout',
                           name='logout'),
                       # Learn more...
                       url(r'^learn/0/$',
                           'accounts.views.learn.learn_0',
                           name='learn_0'),
                       url(r'^learn/1/$',
                           'accounts.views.learn.learn_1',
                           name='learn_1'),
                       url(r'^learn/2/$',
                           'accounts.views.learn.learn_2',
                           name='learn_2'),

                       url(r'^register$',
                           'accounts.views.other.register',
                           name='register'),
                       url(r'^$',
                           'accounts.views.home_index',
                           name='home'),
                       # DONE: apply session_master
                       url(r'verify_phone',
                           'accounts.views.user.verify_phone',
                           name='verify_phone'),
                        # DONE: apply session_master
                       url(r'^manage_account$',
                           'accounts.views.other.manage_account',
                           name='manage_account'),
                       # DONE: apply session_master
                       url(r'^user/edit$',
                           'accounts.views.user.user_edit',
                           name='user_edit'),
                       # DONE: apply session_master
                       url(r'^user/account_access$',
                           'accounts.views.user.account_access',
                           name='account_access'),
                       # DONE: apply session_master

                       url(r'^admin/', include(admin.site.urls)),

                       # Manage Account
                       # Remove Account

                       )

bbuser/urls.py
from django.conf import *
from registration.backends.default.urls import *
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.core.urlresolvers import reverse_lazy

from accounts.forms.other import RegistrationFormUserTOSAndEmail
from apps.secretqa.views import *
from apps.subacc.views import *

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
                       # Examples:
                       # url(r'^$', 'bbonfhiruser.views.home', name='home'),
                       url(r'^$', 'accounts.views.other.home_index',
                           name='home'),
                       url(r'^about', 'accounts.views.other.about',
                           name='about'),
                       url(r'^whatsnew/$', 'accounts.views.learn.what_is_new',
                           name='whatsnew'),
                       url(r'^accounts/',
                           include('accounts.urls', namespace='accounts')),
                       url(r'^subaccount/',
                           include('apps.subacc.urls', namespace='subaccount')),
                       url(r'^security/',
                           include('apps.secretqa.urls', namespace='security')),
                       # API Entry point
                       # v1api is referenced inside apps.api.urls as v1

                       url(r'^registration/register/$',
                           RegistrationView.as_view(
                               form_class=RegistrationFormUserTOSAndEmail),
                           name='register'),
                       url(r'^logout$',
                           'accounts.views.logout',
                           name='logout'),
                       url(r'^registration/', include(
                           'registration.backends.default.urls', )),
                       url(r'^password/reset/$', auth_views.password_reset,
                           {'post_reset_redirect': reverse_lazy(
                               'password_reset_done')},
                           name='password_reset'),
                       url(
                           r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
                           auth_views.password_reset_confirm,
                           name='password_reset_confirm'),
                       url(r'^password/reset/complete/$',
                           auth_views.password_reset_complete,
                           {'post_reset_redirect': reverse_lazy(
                               'password_reset_complete')},
                           name='password_reset_complete'),
                       url(r'^password/reset/done/$',
                           auth_views.password_reset_done,
                           name='password_reset_done'),
                       url(r'^o/', include('oauth2_provider.urls',
                                           namespace='oauth2_provider')),

                       # OAuth2 Provider Library
                       url(r'^o/', include('oauth2_provider.urls',
                                           namespace='oauth2_provider')),
                       url(r'^admin/', include(admin.site.urls)),
                       # Uncomment the admin/doc line below to enable admin
                       # documentation:
                       url(r'^admin/doc/',
                           include('django.contrib.admindocs.urls')),
                       )
# DONE: Extend user model to enable organization
# TODO: Organization Approval (Test - Automatic)
# TODO: Organization Approval (Prod - Manual)
# DONE: Create Master User for Organization
# DONE: Create Standard User via master user
# DONE: Manage Developer Accounts
# TODO: Reassign Application Ownership within organization
# TODO: Delete accounts account
# TODO: Issue Application Key
# TODO: Manage Application Key
# TODO: Delete Application Key
# TODO: Create BlueButton User Api
# TODO: Change Organization Owner
# TODO: Add IsOwner Flag to User Account
# DONE: Study Bootstrap formatting
# TODO: Pre-load Sites 1 = PROD, 2=TEST 3=LOCALHOST
# TODO: Show date_joined in admin panel
# DONE: Add in OAuth Provider
# TODO: Modify OAuth Model to extend for Organization
# TODO: Integrate OAuthKey in to application key request
# TODO: Implement Multi-factor Authentication (using email to text)

templates/include/footer.html
{# DONE: Fix bottom NavBar #}
{#  DONE: Link to Privacy Statement #}
<div class="container-fluid">
    <div class="row-fluid">
        <div class="nav navbar navbar-nav navbar-fixed-bottom panel-footer footer-wrapper"
        {% if request.META.HTTP_HOST == "localhost:8000" %} style="background-color:lightcyan"{% endif %}>
            <div class="col-md-2">

                <a href="https://github.com/ekivemark/bbofuser"
                    title="{{ settings.APPLICATION_TITLE }} on github"
                    target="_blank"><i class="fa fa-github"></i> {{ settings.APPLICATION_TITLE }}
                </a>

            </div>
            <div class="col-md-2">
                <a href="https://www.cms.gov/About-CMS/Agency-Information/Aboutwebsite/Privacy-Policy.html"
                   title="Medicare Privacy Policy"
                   target="_blank"><i class="fa fa-info-circle"></i> Privacy Policy</a>
            </div>
            <div class="col-md-2">
                {% if request.is_secure %}<i class="fa fa-lock fa-lg" style="color:green"></i>{% endif %}
                <a href="https://www.positivessl.com/multi-domain-ssl-certificate.php"
                style="font-family: arial; font-size: 10px; color: #212121; text-decoration: none;"
                   target="_blank">
                 <img src="https://www.positivessl.com/images-new/PositiveSSL_tl_trans.png"
                      alt="Multi Domain SSL"
                      title="Multi Domain SSL"
                      border="0" height="32px"/></a>
            </div>
            <div class="col-md-6">

            </div>
        </div>
    </div>
</div>

templates/include/head.html
{% load staticfiles %}
<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<meta name="description"
      content="BlueButton 2.0"/>
<link href="{% static 'img/layout/favicon.png' %}" rel="shortcut icon"/>
<link href="{% static 'theme/readable/bootstrap.css' %}"
      rel="stylesheet">

<link href="{% static 'font-awesome/css/font-awesome.min.css' %}"
      rel="stylesheet">

<script src="{% static 'js/jquery-1.8.1.min.js' %}"></script>
<script src="{% static 'js/less-1.3.0.min.js' %}"></script>
<script src="{% static 'bootstrap/js/bootstrap.js' %}"></script>

templates/include/messages.html
{% if messages %}

    <div class="messages">
        <ul>
            Messages go here....
            {% for message in messages %}
                <li{% if message.tags %}
                    class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    </div>

{% endif %}

templates/include/top-nav.html
{% load i18n %}
{% load staticfiles %}

<div class="container-fluid">
    <div class="navbar navbar-default navbar-fixed-top">
{% comment %}
Add a color to the NavBar if we are on localhost:8000
Just to avoid confusion...
{% endcomment %}
        <ul class="nav navbar-nav">
            <li>
                <a href="{% if request.session.auth_device %}{% url 'api:home' %}
                {% else %}{% url 'home' %}{% endif %}" contenteditable="false"
                   class="navbar-brand">
                    <img src="{% static 'img/layout/blue-button-trim.png' %}"
                     style="vertical-align:middle;display:inline-block;max-height:100%;max-width:100%"
                     alt="{{ settings.APPLICATION_TITLE }}">
                </a>
            </li>
            <li>
                <a class="" href="{% url 'home' %}"
                   contenteditable="false" title="{{ settings.APPLICATION_TITLE }} Home"><i class="fa fa-home fa-lg"></i></a>
            </li>
            {% if user.is_authenticated and request.session.auth_master %}
            <li>
                <a class="" href="{% url 'home' %}"
                   contenteditable="false" title="{{ settings.APPLICATION_TITLE }} Home">{{ settings.APPLICATION_TITLE }}<br>Home
                </a>
            </li>
            {% comment %}<li>
                <a href="{% url 'api:home' %}" class=""
                   contenteditable="false" title="BlueButton API Access"><i class="fa fa-bolt"></i> API
                </a>
            </li>{% endcomment %}
            {% comment %}<li>
                {# DONE: create /accounts/app_management - redirect to accounts:manage_account #}
                <a href="{% url 'accounts:manage_account' %}">
                    <i class="fa fa-cogs"></i>{% trans " My Dashboard" %}</a>
            </li>{% endcomment %}
            {% else %}
                <li>
                    <a href="{% url 'accounts:sms_code' %}?next=/" title="Login"><i class="fa fa-sign-in"></i> {% trans "Login" %}</a>
                </li>
                <li>
                    <a href="{% url 'register' %}" title="Register"><i class="fa fa-check-square-o"></i> {% trans "Register" %}</a>
                </li>
            {% endif %}
                <li class="dropdown" id="menu1">
                    <a href="#" class="btn dropdown-toggle"
                   data-toggle="dropdown"><i class="fa fa-info-circle"></i> Learn More<span
                        class="caret"></span></a>
                    <ul class="dropdown-menu" id="menu1" role="menu">
                        <li>
                            <a href="{% url 'accounts:learn_0' %}" title="Learn More">{% trans "Learn More" %}</a>
                        </li>
                        <li>
                            <a href="{% url 'about' %}" title="About {{ settings.APPLICATION_TITLE }}">{% trans "About" %}</a>
                        </li>
                        <li>
                            <a href="{% url 'whatsnew' %}" title="What's New">{% trans "What's New" %}</a>
                        </li>
                    </ul>
                </li>

{#            <li class="divider-vertical"></li>#}

            <li class="dropdown" id="menu2">
                <a href="#" class="btn dropdown-toggle"
                   data-toggle="dropdown"><i class="fa fa-question-circle"></i> Help<span
                        class="caret"></span></a>
                <ul class="dropdown-menu" id="menu2" role="menu">
                    {# TODO: Create /accounts/documentation page  #}
                    <li><a href="/api/documentation" class="">Documentation</a>
                    </li>
                    {# TODO: /accounts/support page  #}
                    <li><a href="/api/support" class="">Support</a>
                    </li>
                    <li class="divider"></li>
 {% comment %}                   <li>
                        <a href="{% url 'api:home' %}" class=""
                                contenteditable="false">API
                        </a>

                    </li>
{% endcomment %}                    {# DONE: /admin access page  #}
                    {% if user.is_admin and request.session.auth_master%}
                        <li class="divider"></li>
                        <li><a href="/admin" class="">Admin</a></li>
                    {% endif %}
                </ul>
            </li>
        </ul>
        {%  if user.is_authenticated %}
        <ul class="nav navbar-nav navbar-right">
            {% if request.session.auth_master %}
                <li>
                    <a href="{%  url 'accounts:manage_account' %}" title="My Account Dashboard">
                        [<i class="fa fa-cogs"></i> {{ user.first_name }} {{ user.last_name }} ]</a>
                </li>
            {% else %}
                <li>
                    <a href="{%  url 'accounts:account_access' %}">
                    [<i class="fa fa-cogs"></i> {{ user.first_name }} {{ user.last_name }} {% if request.session.auth_device %}
                        <br>via {{ request.session.auth_device }} {% endif %}]</a>
                </li>
            {% endif %}
            <li>
                <a href="{% url "accounts:logout" %}?next=/{% if request.session.auth_device %}api/{% endif %}" title="Logout">
                    {% trans "Logout" %} <i class="fa fa-sign-out"></i>&nbsp;&nbsp;&nbsp;</a>
            </li>

        </ul>
        {% endif %}
    </div>
</div>