accounts/urls.py
"""
 BBofUser: Account Framework top level

"""
from django.conf.urls import (patterns,
                              include,
                              url)
from django.contrib import admin

from accounts.views.user import (verify_phone, user_edit)
from accounts.views.other import (manage_account, logout, login)
from accounts.views.sms import (sms_code, sms_login)

admin.autodiscover()

# TODO: Implement Education Pages
# TODO: Replace Register Page with Education Page
# TODO: Add Link to Medicare Registration Page if User Not in LDAP

# DONE: Identify Modules that require accounts.session_master decorator
urlpatterns = patterns('',
                       # Examples:
                       url(r'^login$',
                           'accounts.views.sms.sms_login',
                           name='login'),
                       url(r'smscode/',
                           'accounts.views.sms.sms_code',
                           name='sms_code'),
                       url(r'^logout$',
                           'accounts.views.logout',
                           name='logout'),
                       # Learn more...
                       url(r'^learn/0/$',
                           'accounts.views.learn.learn_0',
                           name='learn_0'),
                       url(r'^learn/1/$',
                           'accounts.views.learn.learn_1',
                           name='learn_1'),
                       url(r'^learn/2/$',
                           'accounts.views.learn.learn_2',
                           name='learn_2'),

                       url(r'^register$',
                           'accounts.views.other.register',
                           name='register'),
                       url(r'^$',
                           'accounts.views.home_index',
                           name='home'),
                       # DONE: apply session_master
                       url(r'verify_phone',
                           'accounts.views.user.verify_phone',
                           name='verify_phone'),
                        # DONE: apply session_master
                       url(r'^manage_account$',
                           'accounts.views.other.manage_account',
                           name='manage_account'),
                       # DONE: apply session_master
                       url(r'^user/edit$',
                           'accounts.views.user.user_edit',
                           name='user_edit'),
                       # DONE: apply session_master
                       url(r'^user/account_access$',
                           'accounts.views.user.account_access',
                           name='account_access'),
                       # DONE: apply session_master

                       url(r'^admin/', include(admin.site.urls)),

                       # Manage Account
                       # Remove Account

                       )

bbuser/urls.py
from django.conf import *
from registration.backends.default.urls import *
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.core.urlresolvers import reverse_lazy

from accounts.forms.other import RegistrationFormUserTOSAndEmail
from apps.secretqa.views import *
from apps.subacc.views import *

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
                       # Examples:
                       # url(r'^$', 'bbonfhiruser.views.home', name='home'),
                       url(r'^$', 'accounts.views.other.home_index',
                           name='home'),
                       url(r'^about', 'accounts.views.other.about',
                           name='about'),
                       url(r'^whatsnew/$', 'accounts.views.learn.what_is_new',
                           name='whatsnew'),
                       url(r'^accounts/',
                           include('accounts.urls', namespace='accounts')),
                       url(r'^subaccount/',
                           include('apps.subacc.urls', namespace='subaccount')),
                       url(r'^security/',
                           include('apps.secretqa.urls', namespace='security')),
                       # API Entry point
                       # v1api is referenced inside apps.api.urls as v1

                       url(r'^registration/register/$',
                           RegistrationView.as_view(
                               form_class=RegistrationFormUserTOSAndEmail),
                           name='register'),
                       url(r'^logout$',
                           'accounts.views.logout',
                           name='logout'),
                       url(r'^registration/', include(
                           'registration.backends.default.urls', )),
                       url(r'^password/reset/$', auth_views.password_reset,
                           {'post_reset_redirect': reverse_lazy(
                               'password_reset_done')},
                           name='password_reset'),
                       url(
                           r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
                           auth_views.password_reset_confirm,
                           name='password_reset_confirm'),
                       url(r'^password/reset/complete/$',
                           auth_views.password_reset_complete,
                           {'post_reset_redirect': reverse_lazy(
                               'password_reset_complete')},
                           name='password_reset_complete'),
                       url(r'^password/reset/done/$',
                           auth_views.password_reset_done,
                           name='password_reset_done'),
                       url(r'^o/', include('oauth2_provider.urls',
                                           namespace='oauth2_provider')),

                       # OAuth2 Provider Library
                       url(r'^o/', include('oauth2_provider.urls',
                                           namespace='oauth2_provider')),
                       url(r'^admin/', include(admin.site.urls)),
                       # Uncomment the admin/doc line below to enable admin
                       # documentation:
                       url(r'^admin/doc/',
                           include('django.contrib.admindocs.urls')),
                       )
# DONE: Extend user model to enable organization
# TODO: Organization Approval (Test - Automatic)
# TODO: Organization Approval (Prod - Manual)
# DONE: Create Master User for Organization
# DONE: Create Standard User via master user
# DONE: Manage Developer Accounts
# TODO: Reassign Application Ownership within organization
# TODO: Delete accounts account
# TODO: Issue Application Key
# TODO: Manage Application Key
# TODO: Delete Application Key
# TODO: Create BlueButton User Api
# TODO: Change Organization Owner
# TODO: Add IsOwner Flag to User Account
# DONE: Study Bootstrap formatting
# TODO: Pre-load Sites 1 = PROD, 2=TEST 3=LOCALHOST
# TODO: Show date_joined in admin panel
# DONE: Add in OAuth Provider
# TODO: Modify OAuth Model to extend for Organization
# TODO: Integrate OAuthKey in to application key request
# TODO: Implement Multi-factor Authentication (using email to text)

accounts/forms/authenticate.py
"""
developeraccount
FILE: authenticate
Created: 6/22/15 12:31 PM

Remember to add new classes to accounts.forms.__init__.py


"""
__author__ = 'Mark Scrimshire:@ekivemark'
from django import forms
from django.conf import settings

from accounts.models import User


class AuthenticationForm(forms.Form):
    """
    Login form
    """
    if settings.USERNAME_FIELD == "email":
        email = forms.EmailField(widget=forms.widgets.TextInput)
    else:
        username = forms.CharField(widget=forms.widgets.TextInput)

    password = forms.CharField(widget=forms.widgets.PasswordInput)
    sms_code = forms.CharField(widget=forms.PasswordInput,
                               max_length=5,
                               label="SMS Code",
                               required=False)

    class Meta:
        fields = [settings.USERNAME_FIELD, 'password', 'sms_code']


class SMSCodeForm(forms.Form):
    if settings.USERNAME_FIELD == "email":
        email = forms.EmailField(widget=forms.widgets.TextInput,
                                 label="Enter your email address",
                                 help_text="We will ask for your password in the next step.")
    else:
        username = forms.CharField(widget=forms.widgets.TextInput,
                             label="Please enter your username:",
                             help_text="We will ask for your password in the next step.")


class AuthenticationSMSForm(forms.Form):
    """
    Login form
    """
    if settings.USERNAME_FIELD == "email":
        email = forms.EmailField(widget=forms.widgets.TextInput)
    else:
        username = forms.CharField(widget=forms.widgets.TextInput)
    password = forms.CharField(widget=forms.widgets.PasswordInput)
    sms_code = forms.CharField(widget=forms.PasswordInput,
                               max_length=5,
                               label="SMS Code",
                               required=False)
    send_pin = forms.BooleanField(required=False, widget=forms.HiddenInput
                                  )

    # class Meta:
    #    fields = ['email', 'password', 'sms_code']

    def clean(self):
        cleaned_data = super(AuthenticationSMSForm, self).clean()
        if settings.USERNAME_FIELD == "email":
            u = User.objects.get(email=self.cleaned_data['email'])
        else:
            u = User.objects.get(username=self.cleaned_data['username'])
        mfa = u.mfa
        if settings.DEBUG:
            print(self.cleaned_data)
        if (self.cleaned_data.get('sms_code') == "" and mfa):
            if settings.DEBUG:
                print("MFA:%s for %s" % (mfa, u.email))
            raise forms.ValidationError("Pin Code is required")

        return self.cleaned_data

accounts/forms/other.py
"""
accounts
FILE: forms.py
Created: 6/21/15 8:31 PM


"""
__author__ = 'Mark Scrimshire:@ekivemark'

from django import forms
from django.utils.safestring import mark_safe
from registration.forms import (RegistrationFormUniqueEmail,
                                RegistrationFormTermsOfService)

from accounts.models import User


class Email(forms.EmailField):
    def clean(self, value):
        value = value.lower()
        super(Email, self).clean(value)
        try:
            User.objects.get(email=value)
            raise forms.ValidationError(mark_safe(
                "This email is already registered. <br/>Use <a href='/password/reset'>this forgot password</a> link or on the <a href ='/accounts/login?next=/'>login page</a>."))
        except User.DoesNotExist:
            return value


class UserRegistrationForm(forms.ModelForm):
    """
    A form for creating new users. Includes all the required
    fields, plus a repeated password.
    """
    # email will be no longer become username
    email = Email()

    password1 = forms.CharField(widget=forms.PasswordInput(),
                                label="Password")
    password2 = forms.CharField(widget=forms.PasswordInput(),
                                label="Repeat your password")

    fields = ['username', 'email', 'password1', 'password2' ]

    def clean_password(self):
        if self.data['password1'] != self.data['password2']:
            raise forms.ValidationError('Passwords are not the same')
        return self.data['password1']


class RegistrationFormUserTOSAndEmail(UserRegistrationForm,
                                      RegistrationFormUniqueEmail,
                                      RegistrationFormTermsOfService,
                                      ):
    pass


class RegistrationFormTOSAndEmail(
    RegistrationFormUniqueEmail,
    RegistrationFormTermsOfService,
    ):

    pass

accounts/forms/user.py
"""
developeraccount
FILE: user
Created: 7/6/15 10:16 PM


"""
__author__ = 'Mark Scrimshire:@ekivemark'

from django import forms

from accounts.models import User, ACTIVITY_NOTIFY_CHOICES


class User_EditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email',
                  'first_name',
                  'last_name',
                  'mobile',
                  'carrier',
                  'mfa',
                  'notify_activity']


class Verify_Mobile(forms.Form):
    # Mobile Verification Form

    verify_code = forms.CharField(max_length=10)


class Medicare_Connect(forms.Form):
    # Get MyMedicare.gov credentials

    mmg_user = forms.CharField(max_length=250)
    mmg_pwd  = forms.CharField(widget=forms.widgets.PasswordInput)

accounts/views/ldap.py
"""
bbofuser:account
FILE: ldap
Created: 8/11/15 3:17 PM

LDAP Utilities for Account

"""
__author__ = 'Mark Scrimshire:@ekivemark'

from ldap3 import (Server, Connection,
                   ALL, SUBTREE, ANONYMOUS,
                   SIMPLE, SYNC, ASYNC,
                   LDAPExceptionError, LDAPException, LDAPSocketOpenError,
                   LDAPOperationResult,
                   )

from django.conf import settings
from django.contrib import messages


def validate_ldap_user(request, email):
    """ Search LDAP for user
        return email if there is a match
    """
    if settings.DEBUG:
        print("in accounts.views.ldap.validate_ldap_user with email:", email)
    result = {}
    if email == "":
        return result

    if not settings.REMOTE_LDAP_CHECK:
        if settings.DEBUG:
            print("LDAP Remote Checking is set to:", settings.REMOTE_LDAP_CHECK)
        return email.lower()

    ##############
    # REMOTE_LDAP_CHECK is True
    # So we need to we need to reach out to the LDAP Server

    server = Server(settings.AUTH_LDAP_SERVER_URI, get_info=ALL)
    try:
        c = Connection(server, auto_bind=True, raise_exceptions=False)
        bound = c.bind()
        if settings.DEBUG:
            print("Connect:",c)
            print("Bind:", bound)
            pass
    except LDAPSocketOpenError:
        c = {}
        if settings.DEBUG:
            print("Server is not reachable")
            print("Connection Exception:",LDAPOperationResult.__str__)
        messages.error(request,
                       "We are having problems reaching the MyMedicare.gov server"
                       " to check your email address. Try again later.")
        result = "ERROR" + str(LDAPExceptionError) + str(LDAPSocketOpenError)
        return result
    if settings.DEBUG:
        #print("Server_Info:", server.info)
        pass

    # ldap_result = c.search(search_base=settings.AUTH_LDAP_SCOPE,
    #                         search_filter="(objectClass=inetOrgPerson)",
    #                        search_scope=SUBTREE,
    #                        attributes = settings.LDAP_AUTH_GET_FIELDS
    #                        )

    # if settings.DEBUG:
    #     print("LDAP_RESULT for ",settings.AUTH_LDAP_SCOPE)
    #     print("response:",c.response)

    user_scope = "cn=" + email.strip() + "," + settings.AUTH_LDAP_SCOPE

    ldap_email_check = c.search(search_base=user_scope,
                                search_filter="(objectClass=inetOrgPerson)",
                                search_scope=SUBTREE,
                                attributes = settings.LDAP_AUTH_GET_FIELDS
                                )
    if settings.DEBUG:
        # print("LDAP_Result for ",user_scope)
        # print("Response:", c.response)
        pass

    ldap_email = ""
    for r in c.response:
        print(r['dn'],r['attributes'])
        ldap_email = r['attributes']['mail']

        print("LDAP_EMAIL:", ldap_email[0] )
    # Patch
    return ldap_email[0].lower()
    # Patch

accounts/views/learn.py
"""
bbofuser
FILE: learn
Created: 8/10/15 9:18 PM


"""
__author__ = 'Mark Scrimshire:@ekivemark'

from django.conf import settings
from django.shortcuts import render_to_response
from django.template import RequestContext


def learn_0(request):
    # Show Education Page 0

    if settings.DEBUG:
        print(settings.APPLICATION_TITLE, "in accounts.views.learn.learn_0")

    context = {}
    return render_to_response('accounts/education_0.html',
                              RequestContext(request, context, ))

def learn_1(request):
    # Show Education Page 1

    if settings.DEBUG:
        print(settings.APPLICATION_TITLE, "in accounts.views.learn.learn_1")

    context = {}
    return render_to_response('accounts/education_1.html',
                              RequestContext(request, context, ))


def learn_2(request):
    # Show Home Page


    if settings.DEBUG:
        print(settings.APPLICATION_TITLE, "in accounts.views.learn.learn_2")

    context = {}
    return render_to_response('accounts/education_2.html',
                              RequestContext(request, context, ))

def what_is_new(request):
    # Show What New Features are launched  (or coming up)

    if settings.DEBUG:
        print("In accounts.views.learn.what_is_new")

    context = {}
    return render_to_response('whatsnew.html',
                              RequestContext(request, context, ))

accounts/templates/accounts/education_0.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}
{% block extrahead %}
    <script src="{% static 'js/switch_content.js' %}"></script>
{% endblock %}
{% block title %}{% trans "Register for an account" %}{% endblock %}
{% block breadcrumbs %}
    <div class="container">
        <ul class="breadcrumb">
            <li><a href="{% url 'home' %}">Home</a></li>

            <li class="active">Learn</li>
        </ul>
    </div>
{% endblock %}
{% block pagename %}Register{% endblock %}
{% block content %}

            <div class="jqueryOptions col-md-6">
                <h1>A New Generation of BlueButton</h1>

                <h3>Put your health information to work for you</h3>

                <p>MyMedicare.gov introduces a new and advanced BlueButton
                    service. The new
                    features allow you to connect your Medicare information
                    to third party
                    applications that you have chosen to trust.
                    <br>
                    <br>BlueButton 2.0 lets you choose where you want to
                    save and manage your
                    health information. We then make it easy for you to
                    connect your data and
                    keep it up to date.
                    <br>
                </p>
            </div>
<div class="section">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <ul class="pagination pagination-lg">
                    <li>
                        <a href="#">&nbsp;&nbsp;&nbsp;&nbsp;</a>
                    </li>
                    <li>
                        <a href="{% url 'accounts:learn_0' %}">1</a>
                    </li>
                    <li>
                        <a href="{% url 'accounts:learn_1' %}">2</a>
                    </li>
                    <li>
                        <a href="{% url 'accounts:learn_2' %}">3</a>
                    </li>
                    <li>
                        <a href="{% url 'accounts:learn_1' %}">Next</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/education_1.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}
{% block extrahead %}
    <script src="{% static 'js/switch_content.js' %}"></script>
{% endblock %}
{% block title %}{% trans "Register for an account" %}{% endblock %}
{% block breadcrumbs %}
    <div class="container">
        <ul class="breadcrumb">
            <li><a href="{% url 'home' %}">Home</a></li>

            <li class="active">Learn</li>
        </ul>
    </div>
{% endblock %}
{% block pagename %}Register{% endblock %}
{% block content %}

<div class="section">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h1>It's Your Data</h1>

                <h3>Taking Your Data with you</h3>

                <p>When you switch on BlueButton 2.0 you are giving
                    MyMedicare.gov permission
                    to &nbsp;send your data to a third party application.
                    &nbsp;
                    <br>
                    <br>Once your data leaves MyMedicare.gov and is sent to
                    an application you
                    have chosen we no longer control that information. You
                    do. Before you connect
                    an application to your MyMedicare information make sure
                    that you trust
                    that application to take good care of your information.&nbsp;
                    <br>
                    <br>Don't worry. If you change your mind you can come
                    back to your account
                    dashboard on MyMedicare.gov and disconnect the
                    applications you want to
                    stop using. Your dashboard also gives you the option to
                    control how long
                    an application has access to your information. When
                    that time limit is
                    reached we will ask you if you want to extend the time.
                </p>
            </div>

        </div>
    </div>
</div>
<div class="section">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <ul class="pagination pagination-lg">
                    <li>
                        <a href="{% url 'accounts:learn_0' %}">Prev</a>
                    </li>
                    <li>
                        <a href="{% url 'accounts:learn_0' %}">1</a>
                    </li>
                    <li>
                        <a href="{% url 'accounts:learn_1' %}">2</a>
                    </li>
                    <li>
                        <a href="{% url 'accounts:learn_2' %}">3</a>
                    </li>
                    <li>
                        <a href="{% url 'accounts:learn_2' %}">Next</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
{%  endblock %}

accounts/templates/accounts/education_2.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}
{% block extrahead %}
    <script src="{% static 'js/switch_content.js' %}"></script>
{% endblock %}
{% block title %}{% trans "Register for an account" %}{% endblock %}
{% block breadcrumbs %}
    <div class="container">
        <ul class="breadcrumb">
            <li><a href="{% url 'home' %}">Home</a></li>

            <li class="active">Learn</li>
        </ul>
    </div>
{% endblock %}
{% block pagename %}Register{% endblock %}
{% block content %}

<div class="section">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h1>So you want to switch on BlueButton 2.0</h1>

                <h3>Here are the next steps:</h3>

                <p><b>1.</b> We will ask you to "sign" a form confirming that you
                    want to be able
                    to send your health information to applications of YOUR
                    choosing.
                    <br>
                    <b>2.</b> We will ask you a series of questions to help us
                    confirm that you are
                    the person asking for your data.
                    <br>
                    <b>3.</b> We will ask you to update your profile with
                    phone information. This will let us offer you the option
                    to use a pin code as an extra layer of
                    security when connecting an application to your
                    MyMedicare information.
                    <br>
                    <br>We will send you a message to your registered email
                    address to confirm each step that you complete.
                    <br>
                    <br>The final email message in the sign up process will
                    have a link that you
                    must click on to activate BlueButton 2.0 on your
                    account.&nbsp;
                    <br>
                    <br>As a security safeguard we will also send a message
                    to you whenever an
                    application is approved to access your MyMedicare.gov
                    record.&nbsp;</p>
            </div>

        </div>
        <div class="row">
            <div class="col-md-5">
                <a href="{% url 'register' %}" class="active btn btn-block btn-lg btn-success">
                    Yes, Register and switch on BlueButton 2.0</a>
            </div>
            <div class="col-md-2">
                <a href="{% url 'home' %}" class="btn btn-danger btn-lg">Cancel</a>
            </div>
            <div class="col-md-5"></div>
        </div>
        <div class="row">
            <div class="col-md-12"></div>
        </div>
    </div>
</div>
<div class="section">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <ul class="pagination pagination-lg">
                    <li>
                        <a href="{% url 'accounts:learn_1' %}">Prev</a>
                    </li>
                    <li>
                        <a href="{% url 'accounts:learn_0' %}">1</a>
                    </li>
                    <li>
                        <a href="{% url 'accounts:learn_1' %}">2</a>
                    </li>
                    <li>
                        <a href="{% url 'accounts:learn_2' %}">3</a>
                    </li>
                    <li>
                        <a href="#">&nbsp;&nbsp;&nbsp;&nbsp;</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Log in" %}{% endblock %}
{% block breadcrumbs %}
    <div class="container">
        <ul class="breadcrumb">
            <li><a href="{% url 'home' %}">Home</a></li>
            <li class="active">Login[2]</li>
        </ul>
    </div>
{% endblock %}
{% block pagename %}Log in (Step 2){% endblock %}
{% block content %}
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="active btn btn-lg btn-success"
               name="login" value="{% trans 'Login' %}"/>
        <input type="submit" class="active btn btn-lg btn-fail"
               name="login" value="{% trans 'Resend Code' %}"/>

        <input type="hidden" name="next" value="{{ next }}"/>
    </form>

    <p>{% trans "Forgot your password?" %} <a
            href="{% url 'password_reset' %}">{% trans "Reset it" %}</a>.
    </p>
    <p>{% trans "Not a member?" %} <a
            href="{% url 'register' %}">{% trans "Register" %}</a>.</p>
{% endblock %}


{% comment %}
**registration/login.html**

It's your responsibility to provide the login form in a template called
registration/login.html by default. This template gets passed four
template context variables:

``form``
    A Form object representing the login form. See the forms
    documentation for more on Form objects.

``next``
    The URL to redirect to after successful login. This may contain a
    query string, too.

``site``
    The current Site, according to the SITE_ID setting. If you don't
    have the site framework installed, this will be set to an instance
    of RequestSite, which derives the site name and domain from the
    current HttpRequest.

``site_name``
    An alias for site.name. If you don't have the site framework
    installed, this will be set to the value of
    request.META['SERVER_NAME']. For more on sites, see The
    "sites" framework.
{% endcomment %}

accounts/templates/accounts/logout.html
{% extends "registration/registration_base.html" %}
{% load i18n %}

{% block title %}{% trans "Logged out" %}{% endblock %}
{% block pagename %}Logout{% endblock %}
{% block content %}
    <p>{% trans "Successfully logged out" %}.</p>
{% endblock %}

accounts/templates/accounts/user_edit.html
{% extends "base.html" %}
{% block pretitle %}Edit Profile{% endblock %}
{% block extra_head %}


{% endblock %}
{% block breadcrumbs %}
       <div class="container">
        <ul class="breadcrumb">
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="{% url 'accounts:manage_account' %}">My Dashboard</a></li>
            <li class="active">Edit Profile</li>
        </ul>
    </div>
{% endblock %}

{% block pagename %}Edit Profile ({{ user }}){% endblock %}
{% block content %}

    <div class="section">
        <div class="container">
            <div class="row">
                <form class="form-horizontal" method="post" action=""
                      xmlns="http://www.w3.org/1999/html">
                    <fieldset>
                        <div class="form-group">
                            <div class="col-lg-6">
                    {% csrf_token %}

                                <table class="table table-hover table-striped">
                                {{ form.as_table }}
                                </table>
                                <div class="row">
                                    <div class="col-lg-10">
                                        <input class="btn-success btn-lg" type="submit"
                                            value="Save"/>
                                    </div>
                                    <div class="col-lg-2 right">
                                        <a href="{% url "accounts:manage_account" %}"><input
                                            type="button" class="btn-danger"
                                            value="Cancel"/></a>
                                    </div>
                                </div>
                             </div>
                        </div>
                    </fieldset>
                </form>

            </div>
        </div>
    </div>





{% endblock %}

accounts/templates/accounts/verify_code.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Verify Mobile Phone" %}{% endblock %}
{% block breadcrumbs %}
    <div class="container">
        <ul class="breadcrumb">
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="{% url 'accounts:manage_account' %}">My Dashboard</a></li>
            <li class="active">Verify Phone</li>
        </ul>
    </div>
{% endblock %}
{% block pagename %}Verify Phone{% endblock %}

{% block content %}

    <form method="post" action="">
        {% csrf_token %}


        <p>Verification Code:</p>

        <p>{{ form.verify_code }}</p>
        <p>Enter the code that you should have received on your mobile phone.</p>
        <p>
            <input type="submit" class="active btn btn-lg btn-success"
                   name="Confirm" value="{% trans 'Confirm' %}"/>
        </p>
        <p><a href="{% url 'accounts:verify_phone' %}"
                       class="btn btn-info">
                        {% trans 'Resend Verification Code' %}
                        </a>
                    </p>
        <input type="hidden" name="next" value="{% url 'accounts:manage_account' %}"/>
    </form>

{% endblock %}