accounts/urls.py
"""
 BBofUser: Account Framework top level

"""
from django.conf.urls import (patterns,
                              include,
                              url)
from django.contrib import admin

from accounts.views.user import (verify_phone, user_edit)
from accounts.views.other import (manage_account, logout, login)
from accounts.views.sms import (sms_code, sms_login)

admin.autodiscover()

# TODO: Implement Education Pages
# TODO: Replace Register Page with Education Page
# TODO: Add Link to Medicare Registration Page if User Not in LDAP

# DONE: Identify Modules that require accounts.session_master decorator
urlpatterns = patterns('',
                       # Examples:
                       url(r'^login$',
                           'accounts.views.sms.sms_login',
                           name='login'),
                       url(r'smscode/',
                           'accounts.views.sms.sms_code',
                           name='sms_code'),
                       url(r'^logout$',
                           'accounts.views.logout',
                           name='logout'),
                       # Learn more...
                       url(r'^learn/0/$',
                           'accounts.views.learn.learn_0',
                           name='learn_0'),
                       url(r'^learn/1/$',
                           'accounts.views.learn.learn_1',
                           name='learn_1'),
                       url(r'^learn/2/$',
                           'accounts.views.learn.learn_2',
                           name='learn_2'),

                       url(r'^register$',
                           'accounts.views.other.register',
                           name='register'),
                       url(r'^$',
                           'accounts.views.home_index',
                           name='home'),
                       # DONE: apply session_master
                       url(r'verify_phone',
                           'accounts.views.user.verify_phone',
                           name='verify_phone'),
                        # DONE: apply session_master
                       url(r'^manage_account$',
                           'accounts.views.other.manage_account',
                           name='manage_account'),
                       # DONE: apply session_master
                       url(r'^user/edit$',
                           'accounts.views.user.user_edit',
                           name='user_edit'),
                       # DONE: apply session_master
                       url(r'^user/account_access$',
                           'accounts.views.user.account_access',
                           name='account_access'),
                       # DONE: apply session_master

                       url(r'^admin/', include(admin.site.urls)),

                       # Manage Account
                       # Remove Account

                       )

bbuser/urls.py
from django.conf import *
from registration.backends.default.urls import *
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.core.urlresolvers import reverse_lazy

from accounts.forms.other import RegistrationFormUserTOSAndEmail
from apps.secretqa.views import *
from apps.subacc.views import *

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
                       # Examples:
                       # url(r'^$', 'bbonfhiruser.views.home', name='home'),
                       url(r'^$', 'accounts.views.other.home_index',
                           name='home'),
                       url(r'^about', 'accounts.views.other.about',
                           name='about'),
                       url(r'^whatsnew/$', 'accounts.views.learn.what_is_new',
                           name='whatsnew'),
                       url(r'^accounts/',
                           include('accounts.urls', namespace='accounts')),
                       url(r'^subaccount/',
                           include('apps.subacc.urls', namespace='subaccount')),
                       url(r'^security/',
                           include('apps.secretqa.urls', namespace='security')),
                       # API Entry point
                       # v1api is referenced inside apps.api.urls as v1

                       url(r'^registration/register/$',
                           RegistrationView.as_view(
                               form_class=RegistrationFormUserTOSAndEmail),
                           name='register'),
                       url(r'^logout$',
                           'accounts.views.logout',
                           name='logout'),
                       url(r'^registration/', include(
                           'registration.backends.default.urls', )),
                       url(r'^password/reset/$', auth_views.password_reset,
                           {'post_reset_redirect': reverse_lazy(
                               'password_reset_done')},
                           name='password_reset'),
                       url(
                           r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
                           auth_views.password_reset_confirm,
                           name='password_reset_confirm'),
                       url(r'^password/reset/complete/$',
                           auth_views.password_reset_complete,
                           {'post_reset_redirect': reverse_lazy(
                               'password_reset_complete')},
                           name='password_reset_complete'),
                       url(r'^password/reset/done/$',
                           auth_views.password_reset_done,
                           name='password_reset_done'),
                       url(r'^o/', include('oauth2_provider.urls',
                                           namespace='oauth2_provider')),

                       # OAuth2 Provider Library
                       url(r'^o/', include('oauth2_provider.urls',
                                           namespace='oauth2_provider')),
                       url(r'^admin/', include(admin.site.urls)),
                       # Uncomment the admin/doc line below to enable admin
                       # documentation:
                       url(r'^admin/doc/',
                           include('django.contrib.admindocs.urls')),
                       )
# DONE: Extend user model to enable organization
# TODO: Organization Approval (Test - Automatic)
# TODO: Organization Approval (Prod - Manual)
# DONE: Create Master User for Organization
# DONE: Create Standard User via master user
# DONE: Manage Developer Accounts
# TODO: Reassign Application Ownership within organization
# TODO: Delete accounts account
# TODO: Issue Application Key
# TODO: Manage Application Key
# TODO: Delete Application Key
# TODO: Create BlueButton User Api
# TODO: Change Organization Owner
# TODO: Add IsOwner Flag to User Account
# DONE: Study Bootstrap formatting
# TODO: Pre-load Sites 1 = PROD, 2=TEST 3=LOCALHOST
# TODO: Show date_joined in admin panel
# DONE: Add in OAuth Provider
# TODO: Modify OAuth Model to extend for Organization
# TODO: Integrate OAuthKey in to application key request
# TODO: Implement Multi-factor Authentication (using email to text)

accounts/forms/authenticate.py
"""
developeraccount
FILE: authenticate
Created: 6/22/15 12:31 PM

Remember to add new classes to accounts.forms.__init__.py


"""
__author__ = 'Mark Scrimshire:@ekivemark'
from django import forms
from django.conf import settings

from accounts.models import User


class AuthenticationForm(forms.Form):
    """
    Login form
    """
    if settings.USERNAME_FIELD == "email":
        email = forms.EmailField(widget=forms.widgets.TextInput)
    else:
        username = forms.CharField(widget=forms.widgets.TextInput)

    password = forms.CharField(widget=forms.widgets.PasswordInput)
    sms_code = forms.CharField(widget=forms.PasswordInput,
                               max_length=5,
                               label="SMS Code",
                               required=False)

    class Meta:
        fields = [settings.USERNAME_FIELD, 'password', 'sms_code']


class SMSCodeForm(forms.Form):
    if settings.USERNAME_FIELD == "email":
        email = forms.EmailField(widget=forms.widgets.TextInput,
                                 label="Enter your email address",
                                 help_text="We will ask for your password in the next step.")
    else:
        username = forms.CharField(widget=forms.widgets.TextInput,
                             label="Please enter your username:",
                             help_text="We will ask for your password in the next step.")


class AuthenticationSMSForm(forms.Form):
    """
    Login form
    """
    if settings.USERNAME_FIELD == "email":
        email = forms.EmailField(widget=forms.widgets.TextInput)
    else:
        username = forms.CharField(widget=forms.widgets.TextInput)
    password = forms.CharField(widget=forms.widgets.PasswordInput)
    sms_code = forms.CharField(widget=forms.PasswordInput,
                               max_length=5,
                               label="SMS Code",
                               required=False)
    send_pin = forms.BooleanField(required=False, widget=forms.HiddenInput
                                  )

    # class Meta:
    #    fields = ['email', 'password', 'sms_code']

    def clean(self):
        cleaned_data = super(AuthenticationSMSForm, self).clean()
        if settings.USERNAME_FIELD == "email":
            u = User.objects.get(email=self.cleaned_data['email'])
        else:
            u = User.objects.get(username=self.cleaned_data['username'])
        mfa = u.mfa
        if settings.DEBUG:
            print(self.cleaned_data)
        if (self.cleaned_data.get('sms_code') == "" and mfa):
            if settings.DEBUG:
                print("MFA:%s for %s" % (mfa, u.email))
            raise forms.ValidationError("Pin Code is required")

        return self.cleaned_data

accounts/forms/other.py
"""
accounts
FILE: forms.py
Created: 6/21/15 8:31 PM


"""
__author__ = 'Mark Scrimshire:@ekivemark'

from django import forms
from django.utils.safestring import mark_safe
from registration.forms import (RegistrationFormUniqueEmail,
                                RegistrationFormTermsOfService)

from accounts.models import User


class Email(forms.EmailField):
    def clean(self, value):
        value = value.lower()
        super(Email, self).clean(value)
        try:
            User.objects.get(email=value)
            raise forms.ValidationError(mark_safe(
                "This email is already registered. <br/>Use <a href='/password/reset'>this forgot password</a> link or on the <a href ='/accounts/login?next=/'>login page</a>."))
        except User.DoesNotExist:
            return value


class UserRegistrationForm(forms.ModelForm):
    """
    A form for creating new users. Includes all the required
    fields, plus a repeated password.
    """
    # email will be no longer become username
    email = Email()

    password1 = forms.CharField(widget=forms.PasswordInput(),
                                label="Password")
    password2 = forms.CharField(widget=forms.PasswordInput(),
                                label="Repeat your password")

    fields = ['username', 'email', 'password1', 'password2' ]

    def clean_password(self):
        if self.data['password1'] != self.data['password2']:
            raise forms.ValidationError('Passwords are not the same')
        return self.data['password1']


class RegistrationFormUserTOSAndEmail(UserRegistrationForm,
                                      RegistrationFormUniqueEmail,
                                      RegistrationFormTermsOfService,
                                      ):
    pass


class RegistrationFormTOSAndEmail(
    RegistrationFormUniqueEmail,
    RegistrationFormTermsOfService,
    ):

    pass

accounts/forms/user.py
"""
developeraccount
FILE: user
Created: 7/6/15 10:16 PM


"""
__author__ = 'Mark Scrimshire:@ekivemark'

from django import forms

from accounts.models import User, ACTIVITY_NOTIFY_CHOICES


class User_EditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email',
                  'first_name',
                  'last_name',
                  'mobile',
                  'carrier',
                  'mfa',
                  'notify_activity']


class Verify_Mobile(forms.Form):
    # Mobile Verification Form

    verify_code = forms.CharField(max_length=10)


class Medicare_Connect(forms.Form):
    # Get MyMedicare.gov credentials

    mmg_user = forms.CharField(max_length=250)
    mmg_pwd  = forms.CharField(widget=forms.widgets.PasswordInput)

accounts/views/ldap.py
"""
bbofuser:account
FILE: ldap
Created: 8/11/15 3:17 PM

LDAP Utilities for Account

"""
__author__ = 'Mark Scrimshire:@ekivemark'

from ldap3 import (Server, Connection,
                   ALL, SUBTREE, ANONYMOUS,
                   SIMPLE, SYNC, ASYNC,
                   LDAPExceptionError, LDAPException, LDAPSocketOpenError,
                   LDAPOperationResult,
                   )

from django.conf import settings
from django.contrib import messages


def validate_ldap_user(request, email):
    """ Search LDAP for user
        return email if there is a match
    """
    if settings.DEBUG:
        print("in accounts.views.ldap.validate_ldap_user with email:", email)
    result = {}
    if email == "":
        return result

    if not settings.REMOTE_LDAP_CHECK:
        if settings.DEBUG:
            print("LDAP Remote Checking is set to:", settings.REMOTE_LDAP_CHECK)
        return email.lower()

    ##############
    # REMOTE_LDAP_CHECK is True
    # So we need to we need to reach out to the LDAP Server

    server = Server(settings.AUTH_LDAP_SERVER_URI, get_info=ALL)
    try:
        c = Connection(server, auto_bind=True, raise_exceptions=False)
        bound = c.bind()
        if settings.DEBUG:
            print("Connect:",c)
            print("Bind:", bound)
            pass
    except LDAPSocketOpenError:
        c = {}
        if settings.DEBUG:
            print("Server is not reachable")
            print("Connection Exception:",LDAPOperationResult.__str__)
        messages.error(request,
                       "We are having problems reaching the MyMedicare.gov server"
                       " to check your email address. Try again later.")
        result = "ERROR" + str(LDAPExceptionError) + str(LDAPSocketOpenError)
        return result
    if settings.DEBUG:
        #print("Server_Info:", server.info)
        pass

    # ldap_result = c.search(search_base=settings.AUTH_LDAP_SCOPE,
    #                         search_filter="(objectClass=inetOrgPerson)",
    #                        search_scope=SUBTREE,
    #                        attributes = settings.LDAP_AUTH_GET_FIELDS
    #                        )

    # if settings.DEBUG:
    #     print("LDAP_RESULT for ",settings.AUTH_LDAP_SCOPE)
    #     print("response:",c.response)

    user_scope = "cn=" + email.strip() + "," + settings.AUTH_LDAP_SCOPE

    ldap_email_check = c.search(search_base=user_scope,
                                search_filter="(objectClass=inetOrgPerson)",
                                search_scope=SUBTREE,
                                attributes = settings.LDAP_AUTH_GET_FIELDS
                                )
    if settings.DEBUG:
        # print("LDAP_Result for ",user_scope)
        # print("Response:", c.response)
        pass

    ldap_email = ""
    for r in c.response:
        print(r['dn'],r['attributes'])
        ldap_email = r['attributes']['mail']

        print("LDAP_EMAIL:", ldap_email[0] )
    # Patch
    return ldap_email[0].lower()
    # Patch

accounts/views/learn.py
"""
bbofuser
FILE: learn
Created: 8/10/15 9:18 PM


"""
__author__ = 'Mark Scrimshire:@ekivemark'

from django.conf import settings
from django.shortcuts import render_to_response
from django.template import RequestContext


def learn_0(request):
    # Show Education Page 0

    if settings.DEBUG:
        print(settings.APPLICATION_TITLE, "in accounts.views.learn.learn_0")

    context = {}
    return render_to_response('accounts/education_0.html',
                              RequestContext(request, context, ))

def learn_1(request):
    # Show Education Page 1

    if settings.DEBUG:
        print(settings.APPLICATION_TITLE, "in accounts.views.learn.learn_1")

    context = {}
    return render_to_response('accounts/education_1.html',
                              RequestContext(request, context, ))


def learn_2(request):
    # Show Home Page


    if settings.DEBUG:
        print(settings.APPLICATION_TITLE, "in accounts.views.learn.learn_2")

    context = {}
    return render_to_response('accounts/education_2.html',
                              RequestContext(request, context, ))

def what_is_new(request):
    # Show What New Features are launched  (or coming up)

    if settings.DEBUG:
        print("In accounts.views.learn.what_is_new")

    context = {}
    return render_to_response('whatsnew.html',
                              RequestContext(request, context, ))

accounts/templates/accounts/include/personal_profile.html
{% load i18n %}
{% if user.is_authenticated %}
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="col-lg-10">
                 <h2>My Profile</h2>
            </div>
             <div class="col-lg-2 align-right">
                <a href="{% url "accounts:user_edit" %}"
                   class="btn btn-success">
                    <i class="fa fa-pencil-square-o fa-1x"></i> {% trans 'Edit' %}</a>
            </div>
        </div>
    </div>

    <div class="container-fluid">

            <div class="list-group">
                <a href="#" class="list-group-item">
                    <h4 class="list-group-item-heading">Name:</h4>
                    <p class="list-group-item-text">{{ user.first_name }}&nbsp; {{ user.last_name }}
                    </p>
                </a>
                <a href="#" class="list-group-item">
                    <h4 class="list-group-item-heading">Email Address:{% if user.notify_activity == "E" %}
                        <i class="fa fa-paper-plane-o" style="color:green"></i>
                        {% endif %}</h4>
                    <p class="list-group-item-text"> {{ user.email }}
                    </p>
                </a>

                {% if user.mobile %}
                <div class="list-group-item">
                    <h4 class="list-group-item-heading">Mobile Phone: {% if user.notify_activity == "T" %}
                        <i class="fa fa-paper-plane-o" style="color:green"></i>
                        {% endif %}</h4>

                    <p class="list-group-item-text">
                            {{ user.mobile }} on {{ user.carrier | upper }}
                        [{% if user.verified_mobile %}Verified
                        {% else %}Unverified{% endif %}]
                    </p>
                    <p class="text-muted">
                            email to text address: {{ mfa_address }}
                    </p>

                    <p>
                        Send PIN Code at Login:
                        {% if user.mfa %}YES{% else %}no{% endif %}
                    </p>
                    <p><a href="{% url 'accounts:verify_phone' %}"
                       class="btn btn-success">
                        <i class="fa fa-mobile fa-2x"></i> {% trans ' Verify My Phone' %}
                        </a>
                    </p>

                </div>
                {% endif %}
            </div>

    </div>
{% else %}

{% endif %}

accounts/templates/accounts/include/subaccount_profile.html
{% load i18n %}

{% if user.is_authenticated %}
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="col-lg-10">
                 <h2>My Sub-accounts</h2>
            </div>
             <div class="col-lg-2 align-right">
                <a href="/subaccount/add"
                   class="btn btn-success">
                    <i class="fa fa-plus-square-o"></i> Add a Sub-account</a>
            </div>
        </div>

    </div>

    <table class="table table-striped table-hover ">
        <thead>
        {% comment %}#DONE: Add active status with icons{% endcomment %}
            <tr>
                <th>Edit</th>
                <th>Active</th>
                <th>Used</th>
                <th>permitted</th>
                <th>Nick name</th>
                <th>User name</th>
                <th>Password key</th>
                <th>Valid Until</th>
                <th>Delete</th>
            </tr>
        </thead>
        {% for device in devices %}
            <tr>
                <td style="text-align:center;">
                    <a href="/subaccount/edit/{{ device.id }}/"><i class="fa fa-pencil-square-o fa-lg"></i></a>
                </td>
                <td style="text-align:center;">
                    {% if device.active %}<i class="fa fa-check-square-o fa-lg" style="color:green"></i>
                    {% else %}<i class="fa fa-square-o fa-lg" style="color:red"></i>{% endif %}
                </td>
                <td style="text-align:center;">
                    {% if device.permitted %}<i class="fa fa-check-square-o fa-lg" style="color:green"></i>
                    {% else %}<i class="fa fa-square-o fa-lg" style="color:red"></i>{% endif %}
                </td>
                <td style="text-align:center">
                    {% if device.used %}<i class="fa fa-toggle-on fa-lg" style="color:green"></i>
                    {% else %}<i class="fa fa-toggle-off fa-lg" style="color:red"></i>{% endif %}
{#  DONE: Add Active Indicator#}
                </td>
                <td>
                    {{ device.device }}
                </td>
                <td>
                    {{ device.account }}
                </td>
                <td>
                    {{ device.password }}
                </td>
                <td>
                    {{ device.valid_until }}
                </td>
                <td style="text-align:center;">
                    <a href="/subaccount/delete/{{ device.id }}/" style="color:red"><i class="fa fa-trash-o fa-fw fa-lg"></i></a>
                </td>

            </tr>
        {% endfor %}
    </table>
{% endif %}