accounts/urls.py
"""
 BBofUser: Account Framework top level

"""
from django.conf.urls import (patterns,
                              include,
                              url)
from django.contrib import admin

from accounts.views.user import (verify_phone, user_edit)
from accounts.views.other import (manage_account, logout, login)
from accounts.views.sms import (sms_code, sms_login)

admin.autodiscover()

# TODO: Implement Education Pages
# TODO: Replace Register Page with Education Page
# TODO: Add Link to Medicare Registration Page if User Not in LDAP

# DONE: Identify Modules that require accounts.session_master decorator
urlpatterns = patterns('',
                       # Examples:
                       url(r'^login$',
                           'accounts.views.sms.sms_login',
                           name='login'),
                       url(r'smscode/',
                           'accounts.views.sms.sms_code',
                           name='sms_code'),
                       url(r'^logout$',
                           'accounts.views.logout',
                           name='logout'),
                       # Learn more...
                       url(r'^learn/0/$',
                           'accounts.views.learn.learn_0',
                           name='learn_0'),
                       url(r'^learn/1/$',
                           'accounts.views.learn.learn_1',
                           name='learn_1'),
                       url(r'^learn/2/$',
                           'accounts.views.learn.learn_2',
                           name='learn_2'),

                       url(r'^register$',
                           'accounts.views.other.register',
                           name='register'),
                       url(r'^$',
                           'accounts.views.home_index',
                           name='home'),
                       # DONE: apply session_master
                       url(r'verify_phone',
                           'accounts.views.user.verify_phone',
                           name='verify_phone'),
                        # DONE: apply session_master
                       url(r'^manage_account$',
                           'accounts.views.other.manage_account',
                           name='manage_account'),
                       # DONE: apply session_master
                       url(r'^user/edit$',
                           'accounts.views.user.user_edit',
                           name='user_edit'),
                       # DONE: apply session_master
                       url(r'^user/account_access$',
                           'accounts.views.user.account_access',
                           name='account_access'),
                       # DONE: apply session_master

                       url(r'^admin/', include(admin.site.urls)),

                       # Manage Account
                       # Remove Account

                       )

apps/subacc/urls.py
"""
bbofuser:device
FILE: urls
Created: 8/3/15 6:00 PM


"""
__author__ = 'Mark Scrimshire:@ekivemark'

from django.conf.urls import (patterns,
                              include,
                              url)
from django.contrib import admin

from apps.subacc.views import *

admin.autodiscover()

urlpatterns = patterns('',
                       # Examples:
                       url(r'^$', 'apps.subacc.views.subacc_index',
                           name='home'),
                       url(r'^add',
                           'apps.subacc.views.subacc_add',
                            name='subacc_add'),
                       url(r'^edit/(?P<pk>[-\w]+)/$',
                           'apps.subacc.views.subacc_edit',
                            name='subacc_edit'),
                       # url(r'^subacc/edit/(?P<pk>[-\w]+)/$',
                       #     'apps.subacc.views.device_edit',
                       #     name='device_edit'),
                       url(r'^delete/(?P<pk>[-\w]+)/$',
                           'apps.subacc.views.Subacc_Delete', name='subacc_delete'),
                       url(r'^login/$',
                           'apps.subacc.views.Subaccount_Login',
                           name='subacc_login'),
                       url(r'^get_permission/$',
                           'apps.subacc.views.ask_user_for_permission',
                           name='ask_permission'),

                       url(r'^admin/', include(admin.site.urls)),

                       )

bbuser/urls.py
from django.conf import *
from registration.backends.default.urls import *
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.core.urlresolvers import reverse_lazy

from accounts.forms.other import RegistrationFormUserTOSAndEmail
from apps.secretqa.views import *
from apps.subacc.views import *

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
                       # Examples:
                       # url(r'^$', 'bbonfhiruser.views.home', name='home'),
                       url(r'^$', 'accounts.views.other.home_index',
                           name='home'),
                       url(r'^about', 'accounts.views.other.about',
                           name='about'),
                       url(r'^whatsnew/$', 'accounts.views.learn.what_is_new',
                           name='whatsnew'),
                       url(r'^accounts/',
                           include('accounts.urls', namespace='accounts')),
                       url(r'^subaccount/',
                           include('apps.subacc.urls', namespace='subaccount')),
                       url(r'^security/',
                           include('apps.secretqa.urls', namespace='security')),
                       # API Entry point
                       # v1api is referenced inside apps.api.urls as v1

                       url(r'^registration/register/$',
                           RegistrationView.as_view(
                               form_class=RegistrationFormUserTOSAndEmail),
                           name='register'),
                       url(r'^logout$',
                           'accounts.views.logout',
                           name='logout'),
                       url(r'^registration/', include(
                           'registration.backends.default.urls', )),
                       url(r'^password/reset/$', auth_views.password_reset,
                           {'post_reset_redirect': reverse_lazy(
                               'password_reset_done')},
                           name='password_reset'),
                       url(
                           r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
                           auth_views.password_reset_confirm,
                           name='password_reset_confirm'),
                       url(r'^password/reset/complete/$',
                           auth_views.password_reset_complete,
                           {'post_reset_redirect': reverse_lazy(
                               'password_reset_complete')},
                           name='password_reset_complete'),
                       url(r'^password/reset/done/$',
                           auth_views.password_reset_done,
                           name='password_reset_done'),
                       url(r'^o/', include('oauth2_provider.urls',
                                           namespace='oauth2_provider')),

                       # OAuth2 Provider Library
                       url(r'^o/', include('oauth2_provider.urls',
                                           namespace='oauth2_provider')),
                       url(r'^admin/', include(admin.site.urls)),
                       # Uncomment the admin/doc line below to enable admin
                       # documentation:
                       url(r'^admin/doc/',
                           include('django.contrib.admindocs.urls')),
                       )
# DONE: Extend user model to enable organization
# TODO: Organization Approval (Test - Automatic)
# TODO: Organization Approval (Prod - Manual)
# DONE: Create Master User for Organization
# DONE: Create Standard User via master user
# DONE: Manage Developer Accounts
# TODO: Reassign Application Ownership within organization
# TODO: Delete accounts account
# TODO: Issue Application Key
# TODO: Manage Application Key
# TODO: Delete Application Key
# TODO: Create BlueButton User Api
# TODO: Change Organization Owner
# TODO: Add IsOwner Flag to User Account
# DONE: Study Bootstrap formatting
# TODO: Pre-load Sites 1 = PROD, 2=TEST 3=LOCALHOST
# TODO: Show date_joined in admin panel
# DONE: Add in OAuth Provider
# TODO: Modify OAuth Model to extend for Organization
# TODO: Integrate OAuthKey in to application key request
# TODO: Implement Multi-factor Authentication (using email to text)

accounts/forms/register.py
"""
developeraccount
FILE: register
Created: 6/22/15 12:31 PM

Remember to add new classes to accounts.forms.__init__.py

"""
__author__ = 'Mark Scrimshire:@ekivemark'

from django import forms

from accounts.models import User


class RegistrationForm(forms.ModelForm):
    """
    Form for registering a new account.
    """
    email = forms.EmailField(widget=forms.EmailInput, label="Email")
    password1 = forms.CharField(widget=forms.PasswordInput,
                                label="Password")
    password2 = forms.CharField(widget=forms.PasswordInput,
                                label="Password (again)")
    first_name = forms.CharField(max_length=50,
                                 widget=forms.TextInput,
                                 label="First name")
    last_name = forms.CharField(max_length=50,
                                widget=forms.TextInput,
                                label="Last name")

    class Meta:
        model = User
        fields = ['username', 'email',
                  'password1', 'password2',
                  'first_name', 'last_name']

    def clean(self):
        """
        Verifies that the values entered into the password fields match

        NOTE: Errors here will appear in ``non_field_errors()`` because it applies to more than one field.
        """
        cleaned_data = super(RegistrationForm, self).clean()
        if 'password1' in self.cleaned_data and 'password2' in self.cleaned_data:
            if self.cleaned_data['password1'] != self.cleaned_data[
                'password2']:
                raise forms.ValidationError(
                    "Passwords don't match. Please enter both fields again.")
        return self.cleaned_data

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user

templates/about.html
 {% extends "base.html" %}
 {% load i18n %}
 {% load staticfiles %}
 {% block pretitle %}{% endblock %}
 {% block extra_head %} {% endblock %}
 {% block breadcrumbs %}
         <div class="container">
        <ul class="breadcrumb">
            <li><a href="{% url 'home' %}">Home</a></li>

            <li class="active">About BlueButton</li>
        </ul>
    </div>
 {%  endblock %}
 {% block pagename %}About{% endblock %}
 {% block content %}

     <div class="row">
         <div class="col-md-12">
             <h3 contenteditable="true">Put Your Medicare Claims Information to Work For You</h3>
         </div>
     </div>
<div class="section">
     <div class="row">
         <div class="col-lg-8">
             <p>
                 <span>
                     <a href="https://www.mymedicare.gov/">MyMedicare.gov's</a>
                 </span>
                 <span>Blue Button provides you an easy way to put your data to work for you
                     in the devices and applications you trust. Switching on the advanced functionality
                     of Medicare's next generation BlueButton service lets you setup unique
                     passwords for each device you use and lets you remove or change the password
                     if you lose a device.&nbsp;
                 </span>
             </p>
             <p>
                 <span>To use this feature you will setup a device profile and copy
                     the unique credentials (a custom user name and password). You can save those
                     credentials and use them whenever you connect to the BlueButton service from that device.
                 </span>
             </p>
         </div>
         <div class="col-md-4">
             <img src="{% static 'img/layout/blue-button.png' %}" style="height:300px">
         </div>
          {%  if request.is_secure %}
             <div class="col-md-4">
             <h4>Securing your data</h4>
             This server is protected with a Security Certificate. All communication with this server
             is encrypted using SSL. Your browser indicates this with a lock icon ( <i class="fa fa-lock fa-lg"></i> ).

            <a href="https://www.positivessl.com/multi-domain-ssl-certificate.php"
                target="_blank"
                style="font-family: arial; font-size: 10px; color: #212121; text-decoration: none;">
                 <img src="https://www.positivessl.com/images-new/PositiveSSL_tl_trans.png"
                      alt="Multi Domain SSL"
                      title="Multi Domain SSL"
                      border="0" /></a><div style="font-family: arial;font-weight:bold;font-size:15px;color:#86BEE0;">
                <a href="https://www.positivessl.com/multi-domain-ssl-certificate.php"
                   target="_blank"
                   style="color:#86BEE0; text-decoration: none;">Multi Domain SSL</a></div>
         </div>
         {% endif %}

     </div>
</div>



 {% endblock %}

templates/account_access.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}

{% block pretitle %}{{ settings.APPLICATION_TITLE }}:API - Access Issue{% endblock %}
{% block extra_head %}
{% endblock %}
{%  block breadcrumbs %}
    <div class="container">
        <ul class="breadcrumb">
            <li class="active">Home</li>
            <li><a href="{% url 'api:home' %}">API</a></li>
            <li class="active">Access Warning</li>
        </ul>
    </div>
{%  endblock %}

{% block pagename %}{{ settings.APPLICATION_TITLE }}:Access Issue{% endblock %}
{% block content %}


    <div class="hero-unit">

        <div class="container-fluid">

            <div class="col-md-8">
                <p>
                    You must login with your master account in order to
                    manage your account preferences. You are currently
                    accessing {{ APPLICATION_TITLE }} via one of the
                    device accounts you created.
                </p>
                <p>
                    This restriction is applied as a security protection
                    for your account information.
                </p>
                <p>
                    You are currently using the following Sub-account:
                </p>
                    <div class="jumbotron">
                        <h2>[ {{ request.session.auth_device }} ]</h2>
                    </div>
                <p>
                    <a href="{% url "accounts:sms_code" %}?next=/"><i class="fa fa-unlock fa-3x" style="color:green"></i>
                        <input  type="button"
                                class="active btn btn-large btn-success"
                                value="{% trans " Login with master account " %}"/></a>
                </p>
            </div>

            <div class="col-md-4"><img
                    src="{% static 'img/layout/blue-button.png' %}"
                    style="height:300px"></div>

        </div>
    </div>


{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>
        {% block pretitle %}{% endblock %}
        {% block title %} {{ APPLICATION_TITLE }} {% endblock %}
    </title>

    {% block head %}
        {% include "include/head.html" %}
    {% endblock %}

    {% block extra_head %}
    {% endblock %}

</head>
<body>
{% include "include/top-nav.html" %}

{% comment %}<div class="alert alert-danger">
            <strong>Upcoming Downtime</strong> CMS's BlueButton APIs will be inaccessible Saturday, August 9th from 8AM - 9AM ET.
            We apologize for the inconvenience. <a href="mailto:support@bbonfhir.com">Contact us</a> with any questions.
        </div>{% endcomment %}


    <div class="col-lg-12">
        {% block breadcrumbs %}
        {% endblock %}
    </div>
{% block messages %}
{% endblock %}
<div class="container">
    <h1>{% block pagename %}{% endblock %}</h1>
    <div class="container">
        {% if messages %}
            {% for message in messages %}
        <div class="alert alert-dismissible alert-{{ message.tags }}">
            {%  if message.tags == "error" %}
                <h4>There was a problem</h4>
            {% elif message.tags == "info" %}
                <h4>Just letting you know...</h4>
            {% elif message.tags == "success" %}
                <h4>That worked...</h4>
            {% else %}
                <h4>System message:</h4>
            {%  endif %}
            <button type="button" class="close" data-dismiss="alert">×</button>
            <p>
                {{ form.errors }}
                {{ message }}
            </p>
        </div>
            {% endfor %}
        {% endif %}

    </div>
    {% block content %}

        {% if template %}{% include template %}{% endif %}
        {{ content|safe }}
    {% endblock %}
</div>

{% include "include/footer.html" %}

</body>

</html>

templates/index.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}

{% block pretitle %}{% endblock %}
{% block extra_head %}
{% endblock %}

{% block breadcrumbs %}
       <div class="container">
        <ul class="breadcrumb">
            <li class="active">Home</li>
        </ul>
    </div>
{% endblock %}
{% block pagename %}Welcome{% endblock %}
{% block content %}


    <div class="hero-unit">

        <h2>{{ settings.APPLICATION_TITLE }}</h2>

        <div class="container-fluid">
                <p>
                    {% if user.is_authenticated and request.session.auth_master %}
                    <a href="{% url 'accounts:manage_account' %}"
                       class="btn btn-primary btn-large">
                        <i class="fa fa-lock fa-lg"></i>  Manage Your Account</a>
                    {% else %}
                        {% if user.is_authenticated and not request.session.auth_master %}
                    You are logged in via a sub-account:
                        <a href="{%  url 'accounts:account_access' %}">
                    [ {{ user.first_name }} {{ user.last_name }} {% if request.session.auth_device %}
                            via {{ request.session.auth_device }} {% endif %}]</a>
                    <p>
                    You need to login with your master account.
                    </p>
                        {% endif %}
                        <div class="col-lg-4">
                        <h4>Login to your account</h4>
                        <a href="{% url "accounts:sms_code" %}?next=/">
                        <i class="fa fa-unlock fa-2x" style="color:green"></i><input
                            type="button"
                            class="active btn btn-large btn-success"
                            value="{% trans " Main Account Login " %}"/></a>
                        </div>
                        <div class="col-lg-4">
                        <h4>Login with a sub-account</h4>
                        <a href="{% url "subaccount:subacc_login" %}?next=/">
                        <i class="fa fa-unlock fa-2x" style="color:lightgreen"></i><input
                            type="button"
                            class="active btn btn-large btn-success"
                            style="color:lightgreen"
                            value="{% trans "Sub-account Login " %}"/></a>
                        </div>
                        <div class="col-lg-4">

                        </div>

                    {% endif %}
                </p>
            <div class="col-md-8">
                <p>
                    BlueButton 2.0 provides you, our Medicare Beneficiaries,
                    with the ability to access your Medicare information with
                    greater flexibility and enhanced security.
                </p>
                <p>
                    Some of the new features include:
                    <li>
                        An advanced interface that provides the ability to
                        search your claims information. You no longer have
                        to download a large file of claims information and
                        manually sift through it to find the information
                        you need.
                    </li>
                    <li>
                        Choose to use your mobile phone to receive a
                        temporary pin code that you enter as part of your
                        account login.
                    </li>
                    <li>
                        Add your own secret questions and answers that we
                        can use as login challenges when we detect that
                        your account is being accessed from a new
                        location or device.
                    </li>
                    <li>
                        Create device specific login credentials. This lets
                        you create custom credentials that you can use to
                        access the BlueButton 2.0 advanced interface.
                    </li>
                    <li>
                        A device dashboard that lets you manage your devices.
                        Disable the credentials, reset device passwords or
                        change when device credentials expire.
                    </li>
                </p>
            </div>

            <div class="col-md-4"><img
                    src="{% static 'img/layout/blue-button.png' %}"
                    style="height:300px">
            </div>

        </div>
    </div>


{% endblock %}

templates/register.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}
{% block extrahead %}
    <script src="{% static 'js/switch_content.js' %}"></script>
{% endblock %}
{% block title %}{% trans "Register for an account" %}{% endblock %}
{% block breadcrumbs %}
    <div class="container">
        <ul class="breadcrumb">
            <li><a href="{% url 'home' %}">Home</a></li>

            <li class="active">Register</li>
        </ul>
    </div>
{% endblock %}
{% block pagename %}Register{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="row">

        <div class="col-md-4">
            <p>
                <br>
            </p>
            <form method="post" action="" xmlns="http://www.w3.org/1999/html">
                {% csrf_token %}
                <table>
                    <tr>
                        <td>
                            {{ form.as_table }}
                        </td>
                    </tr>
                </table>
                <p>
                    <a href="/"><input type="button"
                                       class="btn-danger"
                                       value="Cancel"/></a>
                </p>
                <p>
                    <input class="btn-success btn-lg"
                           type="submit"
                           value="{% trans 'I Agree to the terms - Register Me' %}"/>
                </p>
            </form>
            <p>
                <a href="https://mymedicare.gov/registration.aspx">
                    {% trans "Register on MyMedicare.gov" %}</a>
            </p>
        </div>
        <div class="col-md-8">
            <div class="terms">
                <!--- Template is in bbonfhiruser/templates/developer --->
                {% include "accounts/agree_to_terms.html" %}
            </div>
        </div>
    </div>
</div>
{% endblock %}


{% comment %}
**registration/registration_form.html**
Used to show the form users will fill out to register. By default, has
the following context:

``form``
    The registration form. This will be an instance of some subclass
    of ``django.forms.Form``; consult `Django's forms documentation
    <http://docs.djangoproject.com/en/dev/topics/forms/>`_ for
    information on how to display this in a template.
{% endcomment %}

templates/secretqa_answer.html
<div class="modal hide" id="pop_answerModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title">{{ q }}</h4>
      </div>
      <div class="modal-body">
        <p>{{ a }}</p>
          <p>{{ qa }} | {{ pa }}</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>

      </div>
    </div>
  </div>
</div>

templates/whatsnew.html
 {% extends "base.html" %}
 {% load i18n %}
 {% load staticfiles %}
 {% block pretitle %}{% endblock %}
 {% block extra_head %} {% endblock %}
 {% block breadcrumbs %}
         <div class="container">
        <ul class="breadcrumb">
            <li><a href="{% url 'home' %}">Home</a></li>

            <li class="active">What's New</li>
        </ul>
    </div>
 {%  endblock %}
 {% block pagename %}What's New{% endblock %}
 {% block content %}

     <div class="row">
         <div class="col-md-12">
             <h3 contenteditable="true">What's New with {{ settings.APPLICATION_TITLE }}</h3>
         </div>
     </div>
<div class="section">
     <div class="row-fluid">
         <div class="col-lg-8 well well-large">
             <h4>Send Email on Account Activity[Implemented]
             </h4>
             <p>
                 <p>Send Email when Login occurs
                 </p>
                 <span>
                    Keep beneficiary informed by sending an email when a login occurs.
                     Notify Activity can be set to Email or Text. Text Notification requires the
                     mobile phone on the account to be verified.

                     <p>There will be a dashboard setting to allow this to be switched on and off.</p>
                 </span>
             <p>
{% comment %}
             <h4>
             </h4>
             <p>
                 <span>.&nbsp;
                 </span>
             <p>
{% endcomment %}
         </div>
         <div class="col-md-4">
             <img src="{% static 'img/layout/blue-button.png' %}" style="height:300px">
         </div>
     </div>
    <div class="row-fluid">
       <div class="col-lg-8">
            <h4>Send Email on Account Activity[Implemented]
             </h4>
             <p>
                 <p>Send Email when Login occurs
                 </p>
                 <span>
                    Keep beneficiary informed by sending an email when a login occurs.
                     Notify Activity can be set to Email or Text. Text Notification requires the
                     mobile phone on the account to be verified.

                     <p>There will be a dashboard setting to allow this to be switched on and off.</p>
                 </span>
             <p>

             <h4>Email checked against LDAP[Implemented]
             </h4>
             <p>
                 <p>Email Address is validated against an LDAP Server
                 </p>
                 <span>
                     An account will need to exist on MyMedicare.gov in order
                     to register for BlueButton.

                     <p>This feature will be disabled in the test environment to allow
                     non-Medicare members to test the BlueButton service.</p>
                 </span>
             <p>

             <h4>Account Activation [Implemented]
             </h4>
             <p>
                 <p>Send an email to trigger activation of the account.
                 </p>
                 <span>
                     Registration will leave an account created but not active.
                     An email is generated with a link. The user clicks the link to land at a screen
                     that activates the account.
                 </span>
             <p>
       </div>
       <div class="col-lg-8 hidden">
            <h4>title</h4>
            <p>
                <p>Summary line</p>
                <span>details....</span>
            </p>
       </div>
    </div>
</div>



 {% endblock %}